/**
 * Word-compatible read-only documents.
 * Opens in Microsoft Word as .doc (HTML) — not editable by recipients.
 */

const escapeHtml = (value) =>
  String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

const wordShell = (title, bodyHtml, footerText) => `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <!--[if gte mso 9]>
  <xml>
    <w:WordDocument>
      <w:View>Print</w:View>
      <w:Zoom>100</w:Zoom>
      <w:DoNotPromptForConvert/>
      <w:DoNotEditTemplate/>
      <w:ProtectDocument>true</w:ProtectDocument>
    </w:WordDocument>
  </xml>
  <![endif]-->
  <style>
    body {
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      line-height: 1.5;
      color: #1a1a1a;
      margin: 1in;
      -webkit-user-select: none;
      user-select: none;
    }
    h1 { font-size: 14pt; text-align: center; margin-bottom: 24pt; }
    .meta { margin-bottom: 18pt; }
    .meta dt { font-weight: bold; display: inline; }
    .meta dd { display: inline; margin: 0 12pt 0 4pt; }
    pre.body {
      white-space: pre-wrap;
      font-family: 'Times New Roman', Times, serif;
      font-size: 12pt;
      border: none;
      margin: 0;
      padding: 0;
    }
    .footer {
      margin-top: 36pt;
      padding-top: 12pt;
      border-top: 1px solid #ccc;
      font-size: 9pt;
      color: #666;
      text-align: center;
    }
    .badge {
      display: block;
      text-align: center;
      font-size: 9pt;
      font-weight: bold;
      letter-spacing: 0.08em;
      color: #2d6a4f;
      margin-bottom: 12pt;
    }
  </style>
</head>
<body oncontextmenu="return false" contenteditable="false">
  <div class="badge">OFFICIAL RECORD — READ ONLY — NOT EDITABLE</div>
  ${bodyHtml}
  <div class="footer">${escapeHtml(footerText)}</div>
</body>
</html>`

export const buildReadOnlyWordDocument = ({
  title,
  documentNo,
  bodyText,
  meta = [],
  footer = 'This document is an official record and cannot be edited. Generated by Nyumba-track.',
}) => {
  const metaHtml = meta.length
    ? `<dl class="meta">${meta
        .map(
          (row) =>
            `<div><dt>${escapeHtml(row.label)}:</dt><dd>${escapeHtml(row.value)}</dd></div>`,
        )
        .join('')}</dl>`
    : ''

  const bodyHtml = `
    <h1>${escapeHtml(title)}</h1>
    ${documentNo ? `<p style="text-align:center;font-weight:bold;margin-bottom:18pt;">${escapeHtml(documentNo)}</p>` : ''}
    ${metaHtml}
    <pre class="body">${escapeHtml(bodyText)}</pre>
  `

  return wordShell(title, bodyHtml, footer)
}

export const openReadOnlyWordDocument = (html, filename = 'document.doc') => {
  const blob = new Blob(['\ufeff', html], { type: 'application/msword' })
  const url = URL.createObjectURL(blob)
  const win = window.open(url, '_blank', 'noopener,noreferrer')
  if (!win) {
    URL.revokeObjectURL(url)
    return false
  }
  setTimeout(() => URL.revokeObjectURL(url), 60000)
  return true
}

export const downloadReadOnlyWordDocument = (html, filename = 'document.doc') => {
  const blob = new Blob(['\ufeff', html], { type: 'application/msword' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename.endsWith('.doc') ? filename : `${filename}.doc`
  a.click()
  URL.revokeObjectURL(url)
}
